// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKkYwxJndLOC4L8cUdFafnGJZltvjOXmM',
    appId: '1:488502492063:web:b080310128ecda3ce51baa',
    messagingSenderId: '488502492063',
    projectId: 'medication-48e25',
    authDomain: 'medication-48e25.firebaseapp.com',
    storageBucket: 'medication-48e25.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9QidbK0Wo_lu-78AeQuYmEoSkn-ZyrgQ',
    appId: '1:488502492063:android:df6900ec8e5de7f6e51baa',
    messagingSenderId: '488502492063',
    projectId: 'medication-48e25',
    storageBucket: 'medication-48e25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwHGIAUOyYUBCwpKtWUL-7uAGHFXzjt8E',
    appId: '1:488502492063:ios:d089ed96e6a7c5ece51baa',
    messagingSenderId: '488502492063',
    projectId: 'medication-48e25',
    storageBucket: 'medication-48e25.firebasestorage.app',
    iosBundleId: 'com.example.medication',
  );

}